size: 1000000

filename:
    train       : "train"
    validate    : "validate"
    test        : "test"

ratio:
    train       : 8
    validate    : 1
    test        : 1

blank_split: on
